### ISSUE TITLE
コンストラクタについて

### ISSUE THREAD

**Issue by doutori** [wshino/978-4-8399-6513-6#1]
https://github.com/wshino/978-4-8399-6513-6/blob/be0b84d86e602e5268b04d88176817542f45dd02/8/8-1/8-1-6-2_MetaCoin.sol#L13

コントラクトと同名の関数がコンストラクタだと思うのですが、
v0.4.22 から 同名の関数でのコンストラクタは `Deprecated` （Warn表示が出る）になっていたはずなので、
`constructor` で定義する必要があるかと〜

http://solidity.readthedocs.io/en/v0.4.22/contracts.html

**Comment by wshino** [comment]
ここ直さなきゃですね。ありがとうございます。
