### ISSUE TITLE
Event の呼び出しに関して

### ISSUE THREAD

**Issue by doutori** [wshino/978-4-8399-6513-6#4]
https://github.com/wshino/978-4-8399-6513-6/blob/be0b84d86e602e5268b04d88176817542f45dd02/8/8-1/8-1-6-2_MetaCoin.sol#L21

`v0.4.21` から Event の呼び出しには プレフィックスとして `emit` をつける必要があるようです
http://solidity.readthedocs.io/en/v0.4.21/contracts.html#events

**Comment by wshino** [comment]
進化早い。。！ありがとうございます

**Comment by ecouffes** [comment]
知らなかった！

**Comment by doutori** [comment]
しれっとドキュメントに追加されてるんですよね...
Changelog を割と追っていかないと辛いですね >_<

**Comment by jkcomment** [comment]
知らなかった！
