### ISSUE TITLE
全体的にバーションが古いのでバージョンアップした方が良いのでは？

### ISSUE THREAD

**Issue by jkcomment** [wshino/978-4-8399-6513-6#7]
最新バージョン: 0.4.24(?)
ソースコードのバージョン: 4.0.0

最新バージョンにしなくとも0.4.18 ~ 0.4.23あたりにしておくのはいかがでしょうか！？

**Comment by hrnkoji** [comment]
https://github.com/ethereum/solidity/releases
最新バージョン0.4.23みたいですね。最新でいいと思います！

**Comment by ecouffes** [comment]
@doutori 
doutoriさん、近々取り込まれる事を考慮してだと思うんですが、
0.4.24にされていますが、どうしましょう。

0.4.24 にすべきか、 0.4.23にするか。。。

**Comment by wshino** [comment]
0.4.24はまだリリースされていないのでは。
https://github.com/ethereum/solidity/blob/develop/Changelog.md

**Comment by doutori** [comment]
@ecouffes 
すみません、公式のドキュメントだけ見てて、最新が `v0.4.24` じゃんって思っていたのですが、
まだ `unreleased` ってことに今気づきました；；；；；
https://github.com/ethereum/solidity/blob/develop/Changelog.md

現行に沿う形がいいと思うので、個人的に `0.4.23` の方がいい気がしています。
