### ISSUE TITLE
decimalsの数字

### ISSUE THREAD

**Issue by kameware** [wshino/978-4-8399-6513-6#8]
https://github.com/wshino/978-4-8399-6513-6/blob/c8a86f130c02e52fdb956867850ae8026c7ddbcd/8/8-2/8-2-3-1_DappsToken.sol#L12

18だとビルドできませんでした。
18ではなくて、1000e18ではないでしょうか？
書籍の文章も18になっています。

**Comment by wshino** [comment]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/examples/SimpleToken.sol#L17
18だとどんなエラーが出ていますか？

**Comment by kameware** [comment]
すみません、全く指摘箇所が違ってました。
https://github.com/wshino/978-4-8399-6513-6/blob/c8a86f130c02e52fdb956867850ae8026c7ddbcd/8/8-3/8-3-2-14_2_deploy_dapps_token.js#L4
の;がないです。
コード、書籍共に

**Comment by jkcomment** [comment]
> の;がないです。

JavaScriptって行末に;なくても普通に動くはずなんですけど、、

**Comment by kameware** [comment]
あれ？じゃあ単純に僕がほんのe18に気づかなかっただけかもしれません。
なんかここにすごい躓いた記憶だけがあるので、再現確認してみます。

**Comment by kameware** [comment]
すみません、8.2と8.3を1.1版でやり直してみましたが特に問題なく動きました。
僕の勘違いでした。
